ALTER TABLE `services`
ADD COLUMN IF NOT EXISTS `slug` VARCHAR(255) AFTER `name`,
ADD COLUMN IF NOT EXISTS `short_desc` TEXT AFTER `slug`,
ADD COLUMN IF NOT EXISTS `description` LONGTEXT AFTER `short_desc`,
ADD COLUMN IF NOT EXISTS `is_featured` TINYINT(1) DEFAULT 0 AFTER `status`,
ADD COLUMN IF NOT EXISTS `rating` DECIMAL(3,2) DEFAULT 0.00 AFTER `is_featured`,
ADD COLUMN IF NOT EXISTS `duration_minutes` INT DEFAULT 60 AFTER `rating`,
ADD COLUMN IF NOT EXISTS `deleted_at` TIMESTAMP NULL DEFAULT NULL AFTER `created_at`;
