<?php

/**
 * BrainCore - SuggestionModel
 *
 * Manages the brain_suggestions table.
 *
 * Suggestions are auto-generated by SuggestionEngine based on
 * patterns found in brain_improvements. Admin reviews and approves.
 * Approved suggestions are converted into real brain_rules.
 *
 * ─── FLOW ────────────────────────────────────────────────────
 * brain_improvements (pattern found)
 *   → SuggestionEngine.analyze()
 *   → brain_suggestions (status=pending)
 *   → Admin: GET /api/admin/suggestions
 *   → Admin: POST /api/admin/suggestions/approve
 *   → brain_rules (new rule created)
 * ────────────────────────────────────────────────────────────
 */

class SuggestionModel
{
    /**
     * Insert a new suggestion.
     * Skips if an identical pending suggestion already exists
     * for the same client + type + pattern (prevents duplicates on repeated runs).
     *
     * @param  string $clientId
     * @param  string $suggestionType   e.g. "rule_suggestion"
     * @param  array  $suggestionData   Structured data (pattern, suggested rule, etc.)
     * @return string|null              UUID of inserted row, or null if skipped
     */
    public static function create(
        string $clientId,
        string $suggestionType,
        array  $suggestionData
    ): ?string {
        $db = getDB();

        // ── Dedup: same client + type + location + category already pending? ──
        $location = $suggestionData['pattern']['location'] ?? '';
        $category = $suggestionData['pattern']['category'] ?? '';

        $checkSql = "
            SELECT id FROM brain_suggestions
            WHERE  client_id        = :client_id
              AND  suggestion_type  = :type
              AND  status           = 'pending'
              AND  JSON_EXTRACT(suggestion_data, '$.pattern.location') = :location
              AND  JSON_EXTRACT(suggestion_data, '$.pattern.category') = :category
            LIMIT 1
        ";

        $check = $db->prepare($checkSql);
        $check->execute([
            ':client_id' => $clientId,
            ':type'      => $suggestionType,
            ':location'  => $location,
            ':category'  => $category,
        ]);

        if ($check->fetch()) {
            return null; // Already pending — skip
        }

        // ── Insert ────────────────────────────────────────────
        $id  = self::generateUuid();
        $sql = "
            INSERT INTO brain_suggestions
                (id, client_id, suggestion_type, suggestion_data, status, created_at)
            VALUES
                (:id, :client_id, :suggestion_type, :suggestion_data, 'pending', NOW())
        ";

        $st = $db->prepare($sql);
        $st->execute([
            ':id'              => $id,
            ':client_id'       => $clientId,
            ':suggestion_type' => $suggestionType,
            ':suggestion_data' => json_encode($suggestionData, JSON_UNESCAPED_UNICODE),
        ]);

        return $id;
    }

    /**
     * Get all pending suggestions, newest first.
     *
     * @param  string|null $clientId  Optional filter
     * @param  int         $limit
     * @return array
     */
    public static function getPending(?string $clientId = null, int $limit = 50): array
    {
        $db     = getDB();
        $where  = ["status = 'pending'"];
        $params = [];

        if ($clientId !== null) {
            $where[]           = 'client_id = :client_id';
            $params[':client_id'] = $clientId;
        }

        $whereStr = implode(' AND ', $where);

        $sql = "
            SELECT id, client_id, suggestion_type, suggestion_data, status, created_at
            FROM   brain_suggestions
            WHERE  $whereStr
            ORDER  BY created_at DESC
            LIMIT  :limit
        ";

        $params[':limit'] = $limit;

        $st = $db->prepare($sql);
        $st->execute($params);
        $rows = $st->fetchAll();

        foreach ($rows as &$row) {
            if (!empty($row['suggestion_data'])) {
                $row['suggestion_data'] = json_decode($row['suggestion_data'], true);
            }
        }

        return $rows;
    }

    /**
     * Find one suggestion by ID.
     *
     * @param  string $id
     * @return array|null
     */
    public static function findById(string $id): ?array
    {
        $db  = getDB();
        $sql = "SELECT * FROM brain_suggestions WHERE id = :id LIMIT 1";
        $st  = $db->prepare($sql);
        $st->execute([':id' => $id]);
        $row = $st->fetch();

        if (!$row) {
            return null;
        }

        if (!empty($row['suggestion_data'])) {
            $row['suggestion_data'] = json_decode($row['suggestion_data'], true);
        }

        return $row;
    }

    /**
     * Update the status of a suggestion.
     * Used when admin approves or rejects.
     *
     * @param  string $id
     * @param  string $status  'approved' | 'rejected'
     * @return bool
     */
    public static function updateStatus(string $id, string $status): bool
    {
        $db  = getDB();
        $sql = "UPDATE brain_suggestions SET status = :status WHERE id = :id";
        $st  = $db->prepare($sql);
        $st->execute([':status' => $status, ':id' => $id]);

        return $st->rowCount() > 0;
    }

    // ──────────────────────────────────────────────────────────
    // PRIVATE
    // ──────────────────────────────────────────────────────────

    private static function generateUuid(): string
    {
        $bytes    = random_bytes(16);
        $bytes[6] = chr((ord($bytes[6]) & 0x0f) | 0x40);
        $bytes[8] = chr((ord($bytes[8]) & 0x3f) | 0x80);

        return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($bytes), 4));
    }
}
