/**
 * WorkToGo Admin Panel — Configuration
 * Edit this file to point the panel at your backend.
 */
const CONFIG = {
  APP_NAME: "WorkToGo",
  APP_VERSION: "1.2.0",
  API_BASE_URL: "/heart/api",
  ADMIN_PREFIX: "/admin",
  REQUEST_TIMEOUT: 15000,
  TOKEN_KEY: "wtg_admin_token",
  REFRESH_TOKEN_KEY: "wtg_admin_refresh",
  SESSION_DURATION: 8 * 60 * 60,
  DEFAULT_PAGE_SIZE: 25,
  MAX_PAGE_SIZE: 100,
  ENABLE_REAL_TIME_LOGS: true,
  ENABLE_EXPORT_CSV: true,
  LOG_POLL_INTERVAL: 10000,
  DASHBOARD_REFRESH: 30000,
  ENDPOINTS: {
    LOGIN:             "/auth/email/login",
    LOGOUT:            "/auth/logout",
    REFRESH:           "/auth/refresh",
    ME:                "/auth/me",
    DASHBOARD_STATS:   "/stats",
    USERS:             "/users",
    USER_BLOCK:        (id) => `/users/${id}/block`,
    USER_UNBLOCK:      (id) => `/users/${id}/unblock`,
    USER_DETAIL:       (id) => `/users/${id}`,
    VENDORS:           "/vendors",
    VENDOR_APPROVE:    (id) => `/vendors/${id}/approve`,
    VENDOR_REJECT:     (id) => `/vendors/${id}/reject`,
    VENDOR_STATUS:     (id) => `/vendors/${id}/status`,
    VENDOR_DETAIL:     (id) => `/vendors/${id}`,
    PRODUCTS:          "/products",
    PRODUCT_STATUS:    (id) => `/products/${id}/status`,
    PRODUCT_DELETE:    (id) => `/products/${id}`,
    SERVICES:          "/services",
    SERVICE_STATUS:    (id) => `/services/${id}/status`,
    ORDERS:            "/orders",
    ORDER_STATUS:      (id) => `/orders/${id}/status`,
    ORDER_CANCEL:      (id) => `/orders/${id}/cancel`,
    ORDER_DETAIL:      (id) => `/orders/${id}`,
    DELIVERIES:        "/deliveries",
    DELIVERY_ASSIGN:   "/deliveries/assign",
    DELIVERY_STATUS:   (id) => `/deliveries/${id}`,
    PAYMENTS:          "/payments",
    SYSTEM_CONFIG:     "/system/config",
    SYSTEM_TOGGLE:     "/system/toggle",
    SYSTEM_EMERGENCY:  "/system/emergency-stop",
    LOGS:              "/logs",
    ACTIVITY:          "/logs/activity",
  },
};
Object.freeze(CONFIG);
